env:
  global:
  - secure: "xjVXf8JwPVqQLwL4vtMqVyI/oe+5dFP/SiR3CCjVX8LKzdhnC4C62XS8z5reIlTIMtbdUdqS45Si4CPTYp7dFKsxx9/HSJHq9NJ8YWs65Z8v4L1izM0hg5hPQ2RJNX7edptYc013asr3BCl1lregBNtdxIpNJWnBIT6R/8y9gku6vH4qhtDHkGon2dIRbbqWgQc1czmXmxnoqlyy8oXo1Rj3tYX7mFS1gJOCzBoyZPKl1o/lAkaSYl9oOpkV/ktZzK00S3jQPnI25NBOevf1oPu0gWAFzlMeq2QZvM2+hqEnaGUdBmHvZo1UJEs2imqafHByf0YqQu0R1NH3W5IrFYTZJe38oMegsNhh58A/b53n9D6Qa/vcIrUEp/dK7/ZeZYiZhjflUf98TPC+Dn0FOwJdX45VZJtx4mDB61amXiTSkflVgItsW+DTDKOwQ1Oc+4ACsI9lF6Iv8lbcVAN1aqEWmWiMzCdopgr/nsMFGEa9b9Zb8uq4M409P0v4Ln8q35hQdycsTFYDOx/rICIdEleJbQCT6Q63EmywnzziDrj1bXzlGxs1UwZfzQSKcGFfAXl6caGylWwpEknsJlnE2KUeSB5PTAxbLq2cuAzroJIiK3P7JbfxNyQLqSaFtAr+uSAsE0x/+YLhwWGzSpwXICZWpcHcv4y2FWlb9vx7nto="
addons:
  coverity_scan:
    project:
      name: vietcali/cov-c
    notification_email: vietcali2000@gmail.com
    build_command: make
    branch_pattern: coverity_scan
language: c
script: make
