language: c

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "WGa2YxdGr9h7P1JIcGNqM5PUEJp/0DRyGXMYZ4+GoTzu9PcHnxd+w9Qr/QatRzOVzgh4l5PLgmE6VwBNQaQhrlfZ+qRZUE9Ve3LGYXhfMyYdxow/exRsLSra0fa8CQEflz9s5egooyjTsMfrpgJS3w2sUtwlNHr8vBvB+RK8r8sRa6zs6PAzQmKw0nFUMTEFmIxVuTJ8OF83kZf5J6rJWmI2Ga5v4gCo8sq/eHe/fP8mNrUMzTywu1lmBzOEVX+6eJXkJ/xLvib66pvlOthdmS3MU8P5UqDDEDsax/OE7u1231BA9zMF5WDTbgxl8vZr/BWnEBoJmTFb2ksF8f/Fsp6HrWt0He9/JX2LqlgChublveXocOtNwNXXcxlpuKHKJztvovFqslUA0ZM4R7303ppT6Y7r8qN8EB+Fe3760d5QUnIsFBGUUSfy5WxoI3cs/BEQRVf4x70ZdnaGh0pee49udMat/fEFloPICDpLaeT8S/W8JvMIgIFOEdw+GQTx9kSOwZJ7oFg2JIDf0mV6P1198xg95kYn1w1jP3/ghbxVue9ker8dHoOezpwiYX8+N2uMCNrQi0p3w/oJbMxXUINxJVDL9PZe7IsVF1ZjkrXgM5Fm8Dqptb3IQ8E1E1HYyf40WDQ1II30/SJYyTN9cpEC13O+T5EltYe90sccs5w="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "vietcali/cov-c"
      description: "coverity-scan test code"
    notification_email: vietcali2000@gmail.com
    build_command_prepend: ""
    build_command: "make"
    branch_pattern: coverity_scan

script: make
