language: c

script: make

env:
  global:
  - secure: "VdWCfc5SOh1sl-7vJQGNyQ"

addons:
  coverity_scan:

    project:
      name: vietcali/cov-c
      
    notification_email: vietcali2000@gmail.com

    build_command: make

    branch_pattern: coverity_scan
