env:
  global:
  - secure: "gy0kp9yIKr3NTBG5GwmXDFPwnoLend84wp7tbZjBCqITN86S20R0MUXb0zoL4oLkfVSOYL6kYDu+7k5rnYy+LjK4/fNhxEsjGdpkHRyMINK19C4+W1UxWzV4ICvhmQawkG3+rkphYTdpkS7bcpKYj1h/DgQvEzIUjfZFpNmG66Mn69lS7DLGRRmfXygVzYRuFh5EmguOSv3LeWZvz/641M6OVmCityY9/bPkrNoVlvvlVxmzNKAQjJVIVk/51kf2JB2NE6Vf4viZFWlRM9RiPwe20g8fPY6Dj/KiwryKRrwnl6tnRxbqrx2Wwb0m6oUsP+3hf1/24yfGhRmbwBlo5ppnUe//sYXEJpj2zdw+QRBAJ/ztlRKQdUMryGYZr/gkeF7+DLeLNIwydFSKThdZLduW4M3LbTX8jir9QSN8AM1dbvO1vSQ0ERbJoTIz9ceuCad0/95aeepC0CUQmzZh6NgOv/AIZgJ4tJvSn766f5Y6I5ghbM4ODqbpdkGh16AoMxM6kKydnHi32QKg/c5AhYo7HiuNoaaRRdScxZ2noFoqxxZ2jkoEzfxVC1pJ190Gepx1KBBUwChY3LeyuDwbG2gFcPzYdctOBCLL8X+myW4OA04kXDBJHyXGhgIRIeY2tQr0J+gsj+oGu564SauGEb7m/cVu9FtbzBaqMkj0mx0="
addons:
  coverity_scan:
    project:
      name: vietcali/cov-c
    notification_email: vietcali2000@gmail.com
    build_command: make
    branch_pattern: coverity_scan
language: c
script: make
